import {  writable } from 'svelte/store';

export const gamma1 = writable(0.5);
export const gamma2 = writable(0.7);
export const gamma3 = writable(0.3);
export const G = writable(0.1);
export const Xmin = writable(1);
export const delSmax1 = writable(.03);
export const delSmax2 = writable(.4);
export const delSmax3 = writable(.8);
export const delCmax = writable(.9);
export const tau = writable(5);
export const K = writable(1);
export const alpha = writable(5);
export const beta = writable(2);
export const mu = writable(0);
export const z1 = writable(0.5);
export const z2 = writable(0.3);
export const z3 = writable(0.7);
export const N = writable(50);
export const foodShort = writable(0.4);
export const foodShortbegin = writable(0);
export const foodShortend = writable(100);
